model_opts:
  name: "Unet"
  args:
    inchannels: 3
    outchannels: 1
    net_depth: 5
    
train_par:
  gpu_to_use: 'cuda:0' # 'cuda:1', select the GPU where you want your training. if 'default' it will use torch.device("cuda" if torch.cuda.is_available() else "cpu")
  random_seed: 'default'
  epochs: 100
  batch_size: 4
  workers: 4
  lr: 0.01
  eval_threshold: 0.5
  patience: 10
  early_stopping_flag: True
  results_path: "results/buildings_512x512"
  optimizer:
    name: 'Adadelta'
  loss_opts:
    name: 'BCEDiceLoss'
    args:
      weight: 0.5 # this is for BCELogits (value will be computed automatically) & BCEDiceLoss (you need to input a value, default: 0.1)
      alpha: 1 # this is only for focal loss
      gamma: 2 # this is only for focal loss

dataset:
  gt_class: "buildings"
  experiment: "exp_CGIAR_buildings"
  data_dir: "../dataset_512x512/"
  train: "data/experiment_buildings_000/train_00_cv_00.csv"
  dev: "data/experiment_buildings_000/dev_00_cv_00.csv"
  test: "data/experiment_buildings_000/test_00.csv"
  cache_data: True
  rescale_factor: 512
