wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    start_time: 1636216593
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      4: 3.6.9
      5: 0.12.6
      8:
      - 5
dataset:
  desc: null
  value: water
model_opts:
  desc: null
  value:
    args:
      inchannels: 3
      net_depth: 5
      outchannels: 1
    name: Unet
train_par:
  desc: null
  value:
    batch: 4
    epochs: 100
    lr: 0.001
    workers: 1
